### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by MartinAyla** [flipxfx/sVim#10]
I love the extension, but there haven't been any updates in a while, even though there are open issues.

Thanks

**Comment by flipxfx** [comment]
I don't want it to be. :( I've just been preoccupied. I'll try starting up again soon. But you are welcome to submit pull requests and I'll check them in.

**Comment by MartinAyla** [comment]
That's great to hear, I find the extension very useful and hope you'll keep updating it (also with the upcoming 10.11 release).
