### ISSUE TITLE
Scrolling down will move a bit up after completing

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#119]
I believe this is a recent behavior and I am not sure what causes it. To replicate:

1. Scroll down with `j` key
2. Stop scrolling with `j` key
3. Window will stop scrolling but then will move window up a bit annoyingly.

I never had this issue before but I can now replicate this behavior across all sites. 😞

**Comment by nikitavoloboev** [comment]
My sVim settings:

```
let scrollstep = 120

" Unmap defaults
unmap "z i"
unmap "z o"
unmap "z 0"
unmap "g i"
unmap "g r"

" Neat shortcuts
map "v" goToInput
map "c" lastClosedTab
" map "q" zoomPageIn
" map "m" zoomPageOut
" map "o" zoomPageIn
map "e" quit
map "d" createHint
map "f" createTabbedHint
map "o" moveTabLeft
map "p" moveTabRight


" Shift mappings
map "shift+i" quit
map "shift+f" lastActiveTab
map "shift+a" firstTab
map "shift+s" lastTab
map "shift+n" scrollFullPageDown
map "shift+m" scrollFullPageUp
"map "shift+m" scrollPageUp
map "shift+r" closeTabsToRight
map "shift+z" lastClosedTabBackground
map "shift+w" closeTabLeft
map "shift+e" closeTabRight
map "shift+z" lastClosedTab
map "shift+d" parentDirectory
map "shift+g" topDirectory
map "shift+z" lastClosedTabBackground
map "shift+h" topDirectory
map "shift+j" goBack
map "shift+k" goForward

" G multi binds
map "g g" showsVimrc

" Amazing navigation 
" map "w" moveTabRight
" map "q" moveTabLeft
map "s" nextTab
map "a" previousTab
map "b" scrollToBottom
map "n" scrollToTop

map ":" toggleReader
map "w" toggleReader

" Settings
let blacklists = ["*://codepen.io/*", "*://draw.io/*", "*://*slack.com/*", "*://codesandbox.io/*", "*://codewars.com/*", "*://discordapp.com/*", "://gitter.im/*"]
```

**Comment by abrookins** [comment]
Ugh. Yes. This started today after I updated to Safari 12.1 (14607.1.40.1.4), Mojave 10.14.4 (18E226).

**Comment by abrookins** [comment]
Looks like a bug with sending window.scrollBy(0, 0). 🙄

**Comment by abrookins** [comment]
PR up for this. However, I'm having trouble with my certificate, so I can't get a build going tonight.

**Comment by abrookins** [comment]
PR updated with a cert-build safariextz file. Though I'm not sure that matters much with the new rules around plugins...

**Comment by nikitavoloboev** [comment]
So how can I can get this extension installed on my browser now?

**Comment by abrookins** [comment]
Thanks to Apple, you'll need to check out that branch and install it manually via Safari's Extension Builder. Then you'd need to do that every time you restart Safari.

**Comment by abrookins** [comment]
In addition to that, Apple has closed the old submission process, so to get this fix for their regression we'd need to convert the plugin to an app store-compatible plugin and submit through that process. Not sure that will ever happen. 🤔

**Comment by nikitavoloboev** [comment]
FML 😞

Anyone started a rewrite of this plugin to the Swift (new version)? I hate Apple for doing this but this plugin is what makes Safari usable aside from its speed.

**Comment by abrookins** [comment]
Same. I only use Safari because of the battery life -- curious how it's so much better than other browsers ...

We've looked into the App store plugin rewrite. @luchenyuxx started it. The problem is that their new API surface is limited. If we do rewrite the plugin, it will have less features. 🤷‍♂️

Apple has also turned open-source plugins into a difficult proposition. I'm not a Mac or iOS dev, so I have no other reason to pay $100/year just to release this plugin. 1-2 years from now, you probably won't find any free Safari plugins anymore, as I suspect they'll all convert to paid plugins, or else add-ons to existing paid apps/services.
