### ISSUE TITLE
Can't click a form button by createHint

### ISSUE THREAD

**Issue by dsdshcym** [flipxfx/sVim#15]
When using `createHint`, a form button will be shown in blue hint. 

But I can't click it by entering the hint on it.

**Comment by chenggiant** [comment]
Same problem here.

**Comment by ahxxm** [comment]
same problem here

**Comment by jaredmichaelwilliams** [comment]
same

**Comment by deepredsky** [comment]
Same issue

**Comment by bsnsk** [comment]
Same issue here.

**Comment by premjg** [comment]
Same Issue

**Comment by rachidcalazans** [comment]
Same issue

**Comment by huangruihaocst** [comment]
Same issue

**Comment by abrookins** [comment]
This should now be fixed in 1.0.5 (https://github.com/flipxfx/sVim/releases/tag/1.0.5).
