### ISSUE TITLE
sVimrc does not work on OS X 10.11

### ISSUE THREAD

**Issue by peidong** [flipxfx/sVim#16]
Hello, I use this sVimrc https://gist.github.com/peidong/44ed75c61e4e939a3288
And this does not work on OS X 10.11.

Thanks

**Comment by bramblex** [comment]
I have the same problem on OS x 10.11.

**Comment by herrbischoff** [comment]
Same here. It won't install on OS X 10.11.

**Comment by flipxfx** [comment]
Does if work if you remove the site parts at the end of the vimrc?

**Comment by eshansingh** [comment]
Yes, it seems OSX El Capitan doesn't support it.

**Comment by flipxfx** [comment]
Well that site part should have never worked. I haven't implemented that in sVim yet. Can everyone confirm that this is their issue? I'll add adding that site specific code to my to-do list.

**Comment by eshansingh** [comment]
No, the plugin doesn't work even with basic functionality and no sVimrc. Not even hjkl. I think in El Capitan Apple changed some wonky thing or the other, I'm not sure.

**Comment by arstum** [comment]
Yes,it's work in my 10.11.2 system.
https://github.com/flipxfx/sVim/releases/tag/1.0.4

**Comment by adamalbrecht** [comment]
My svimrc seems to have no effect. I have sVim 1.04 and OS X 10.11.2

**Comment by wrtsprt** [comment]
10.11.3 (OS X), 1.0.4. sVim, no problems here. sVim probably installed since at least 10.11.2.

**Comment by M-Kepler** [comment]
10.11.6 safari work good with svim

**Comment by flipxfx** [comment]
Closing as the issue was with the sVimrc. It does not currently support site.
