### ISSUE TITLE
Upvote/downvote buttons on SE/Reddit are not recognized by "follow hint"

### ISSUE THREAD

**Issue by x-ji** [flipxfx/sVim#22]
For other Vim emulators on other browsers, normally upvote/downvote buttons are recognized as well, so I can upvote/downvote directly (on StackOverflow/Reddit etc.) via my keyboard. This doesn't seem to be the case on sVim. Any idea on why this might be happening?

**Comment by x-ji** [comment]
Submitted a PR for this one.

**Comment by abrookins** [comment]
Confirmed fixed with 1.0.5 (https://github.com/flipxfx/sVim/releases/tag/1.0.5). :D
