### ISSUE TITLE
Can't get "blacklists" to work

### ISSUE THREAD

**Issue by abrookins** [flipxfx/sVim#24]
Very cool plugin. I'm using Safari 9.0.1 and release 1.0.4. No matter what I add to "blacklists," including the examples listed in the documentation, the plugin still intercepts key presses.

**Comment by wrtsprt** [comment]
I had problems as well. I think at one point there was a prob with the syntax. Anyways this line is working for me now: `let blacklists = ["*://feedly.com/*", "*://mail.google.com/*"]`. What site are you trying? What does your config look like? (Safari 9.0.3, sVim 1.0.4)

**Comment by abrookins** [comment]
I took another look at this. My problem was that I had a syntax error in the config that appeared to have disabled all my changes. Once I tracked it down, the blacklist worked again (and my other settings).

**Comment by 42a375562621634d5231e583caba7375** [comment]
Same here. Uninstalled sVim months ago because could not block youtube and many other websites. The problem was not solved.
