### ISSUE TITLE
does not work in tabs with pages loaded from local disk

### ISSUE THREAD

**Issue by yogesch** [flipxfx/sVim#30]
I just came across something odd: in tabs where the page is loaded from the local disk (i.e. the address bar reads file:///Users/xx/xx/xx.html), the shortcuts do not work (they work just fine on pages loaded over the internet). Any idea if this is expected behavior? I'm using Safari Version 9.1 on El Capitan 10.11.4.

**Comment by flipxfx** [comment]
Yes, this is expected behavior. Safari does not inject plugins into local pages. No way to fix this right now 😢
