### ISSUE TITLE
I would absolutely love to have '/' hotkey be used for text selection

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#34]
Such a feature is currently present in [vimum](https://github.com/philc/vimium) and it works as follows, you press / hotkey and follow it by some text query, it then finds it on the page and you can do with it what you like. You can even go to visual mode after and select the exact text that you need whilst not once touching your trackpad / mouse.

Such a feature would be absolutely amazing to have. I would really love to help with adding it as it seems that the project is a bit abandoned unfortunately. :(

However I don't really know where I can start with adding such functionality. Thank you a lot and I hope someone will consider adding this feature.

**Comment by flipxfx** [comment]
Duplicate with #5
