### ISSUE TITLE
Is it possible to make binding to go to second tab in Safari?

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#57]
You can go to first tab with `g 0`. Is it possible to make similar binding to go to second tab?

**Comment by luchenyuxx** [comment]
@nikitavoloboev safari has `command 2` to do that thing ...

**Comment by nikitavoloboev** [comment]
Can you map a sVim binding to a hotkey? For example bind `g2` to go activate `cmd + w`?

**Comment by luchenyuxx** [comment]
@nikitavoloboev As far as I know, you can't. 
If so, it's like safari allows javascript send system level key event.
What if someone write a script constantly sending `command q` to safari?

**Comment by nikitavoloboev** [comment]
Yeah that makes sense. I just thought perhaps Safari extensions would have this ability.

**Comment by luchenyuxx** [comment]
@nikitavoloboev But something like `map "g 2" goToTab 2` is totally possible in sVim :)
