### ISSUE TITLE
Submit sVim to Safari Extensions Gallery

### ISSUE THREAD

**Issue by abrookins** [flipxfx/sVim#59]
sVim should appear in the Safari Extensions Gallery and auto-update when we release new versions.

TODO:
- [x] Release latest version, 1.0.5
- [x] Submit signed 1.0.5 package to Safari Extensions Gallery
- [x] Do whatever Apple demands afterward

**Comment by jostyee** [comment]
Thanks @abrookins , Safari just notified the update from gallery.

**Comment by abrookins** [comment]
Thanks for letting me know! They didn't even tell me. :D
