### ISSUE TITLE
Blacklisting websites does not work

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#63]
I have this blacklist set up : 

`let blacklists = ["*://codepen.io/*", "*slack.com/*"]`

However when I open any of slack channels, I still am in normal mode.

Thank you for your help.

**Comment by abrookins** [comment]
Can you try `"*://*slack.com/*"`? That works for me.

**Comment by nikitavoloboev** [comment]
That does work. Thank you.

**Comment by abrookins** [comment]
Yes! Success! Maybe worth a docs update.

**Comment by CallumHoward** [comment]
Hi, having trouble here getting any site blacklisted. I have tried variations with the wildcards, like `*youtube.com*` and `*://youtube.com/*` and `*://*youtube.com*`, nothing seems to stick.
My full sVimrc is:
```
let blacklists = ["*://*youtube.com*"]

set scrollstep = 200
set scrollduration = 200

map "kj" normalMode
map "ctrl+d" scrollPageDown
map "ctrl+u" scrollPageUp
map "ctrl+e" scrollDown
map "ctrl+y" scrollUp
```

Safari 10.1.2
sVim 1.0.5
