### ISSUE TITLE
Can settings in .cvimrc be used in sVimrc?

### ISSUE THREAD

**Issue by amarendra** [flipxfx/sVim#64]
Other than slight syntax changes that I notice (please correct me if I am wrong), can the content be used as in cVim?

For e.g. I see cvimrc can have `map j scrollUp` but but svimrc needs `map "q" nextTab`. 

> functionality of sVim will mostly follow the Chrome extension cVim

This is supposed to be limited to functionality or implementation too?

**Comment by abrookins** [comment]
I think "inspired by cVim" is the position, rather than compatibility. Commands in one won't necessarily work in the other.
