### ISSUE TITLE
"unmap" doesn't work

### ISSUE THREAD

**Issue by pessni** [flipxfx/sVim#67]
"unmap" is useless suddenly, neither is "unmapAll". Tried everything, any suggestion?

sVim 1.0.5, Safari 9.0.3 (11601.4.4), EI Caption 10.11.3.

**Comment by abrookins** [comment]
I just tested an `unmap` command and it seems to have worked. Can you provide your configuration, or a minimal set that reproduces the issue?

**Comment by pessni** [comment]
I reset the "set" part with the default content on the help page, and it seems to work just fine now. Thanks a lot!

**Comment by abrookins** [comment]
No problem. Glad you figured it out!
