### ISSUE TITLE
Slow scrolling with j/k on some sites

### ISSUE THREAD

**Issue by abrookins** [flipxfx/sVim#69]
Using the 'j' and 'k' keys for line-based movement are slow on some complex pages (e.g., long Github pull requests with comments). However, the up and down arrow keys perform quickly. Worth checking out.

**Comment by schmeisers** [comment]
Is this because sVim uses smooth scrolling?  When I use <up> and <down> it is a quick jump to the new position, but `j` and `k` smooth scroll.  Is there a way to disable smooth scrolling in sVim?

**Comment by luchenyuxx** [comment]
Please check this #79 #

**Comment by abrookins** [comment]
I haven't seen this in a while; closing.
