### ISSUE TITLE
Can I map something to "g" alone?

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#70]
I tried `map "g" zoomPageIn` but it does not work for some reason. Not sure why. Every other key works.

**Comment by nikitavoloboev** [comment]
Also perhaps related but mapping `map "z" zoomPageIn` does not work well for me too. It zooms in but pressing it repeatedly does not work well. If I map  `map "o" zoomPageIn` instead it works perfectly well.

I have not binded z to anything else too.

**Comment by luchenyuxx** [comment]
By default, "g" works with other key as a combination. For example, "g r" -> toggle reader view.
So bind only "g" to a command won't work. As it will confuse sVim.
Try `map "g g" zoomPageIn` if you want.

**Comment by luchenyuxx** [comment]
See #48

**Comment by nikitavoloboev** [comment]
Thank you @luchenyuxx
