### ISSUE TITLE
sVim inserts extra HTMLs to email sent on web interface.

### ISSUE THREAD

**Issue by gonejack** [flipxfx/sVim#76]
sVim keep appending this extra text to every editable web content like emails blogs that composed on web interface, and users normally won't see this extra on browser until mobile devices which don't care about CSS to show it up. 

```
<div id="sVim-command" style="bottom: 0px; display: none;">-- NORMAL --</div>
```

**Comment by kbro237** [comment]
I've also had this inserted into content edited by Wordpress. There are times when Wordpress gobbles the style and leaves the '--- NORMAL ---' text.

**Comment by luchenyuxx** [comment]
I tried to fix this by avoiding sVim getting initialised in iframes. However, at last, I think it's not a good idea to block sVim in every iframe. Some iframes may still contain some links that an user wants to follow.
I think it's a good idea to add the page which has issue to blacklist.

**Comment by gonejack** [comment]
Curious about how vimium for Chrome works, vimium seems no this problem.
