### ISSUE TITLE
Link hints with multiple copies of a character doesn't work

### ISSUE THREAD

**Issue by eproxus** [flipxfx/sVim#77]
Set link hint characters to a short list of characters (e.g. `abcd`) and generate link hints on a page with a lot of links. When trying to select a hint with copies of a characters, like `AAB` the hint `AB` is selected instead.

**Comment by luchenyuxx** [comment]
This should work in 1.0.6

**Comment by eproxus** [comment]
With 1.0.6 I cannot select any links any more on such a page, neither short nor long.

**Comment by abrookins** [comment]
@eproxus Can you give me the steps to reproduce this? I don't see the issue when testing locally. Is there a particular URL that you can give me that will reproduce?

**Comment by eproxus** [comment]
Seems this is working now, not sure what happened last time.
