### ISSUE TITLE
3 letters shortcuts won't work

### ISSUE THREAD

**Issue by fuzunspm** [flipxfx/sVim#80]
it's working fine when it's 2 letters like "AD AF AJ" but when it's 3 letters like "KKH KKJ KDA" etc it resets after first key pressed. I mean i try to press KKH for example but in the ends it goes to KH because it resets first key pressed

**Comment by luchenyuxx** [comment]
It's the same issue as #77 . I fixed that in my PR.

**Comment by fuzunspm** [comment]
is there any ETA for the next release because at this point it's in unusable state

**Comment by abrookins** [comment]
1.0.6 is now released (https://github.com/flipxfx/sVim/releases/tag/1.0.6) and should arrive automatically via Safari Extensions Gallery when Apple finishes review, which often takes a while.
