### ISSUE TITLE
Stopped working on YouTube

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#82]
It worked before but stopped. 

This is my blacklist:
`let blacklists = ["*://codepen.io/*", "*://draw.io/*", "*://*slack.com/*", "*://codesandbox.io/*", "*://codewars.com/*", "*://discordapp.com/*", "://gitter.im/*"]`

There is no YouTube there and yet it doesn't work. 😞

Thank you for any help.

**Comment by luchenyuxx** [comment]
I failed to reproduce the issue, even with your blacklist.

**Comment by nikitavoloboev** [comment]
The issue went away. It was some particular youtube page it wasn’t working on it seems.
