### ISSUE TITLE
open link in new foreground tab

### ISSUE THREAD

**Issue by ShiranC** [flipxfx/sVim#88]
Is there a command to open link in new **foreground** tab  ?

**Comment by luchenyuxx** [comment]
Currently, there is no such command.

**Comment by ShiranC** [comment]
Thanks @luchenyuxx 

How do I make a formal enhancement request for this feature?

**Comment by luchenyuxx** [comment]
@abrookins Do you think we can add this as an enhancement? It's not complicated to implement.

**Comment by big-ice** [comment]
@luchenyuxx Where can I get the latest release? I really need this feature!🙏

**Comment by luchenyuxx** [comment]
@big-ice Normally, normally we wait @abrookins process the pull request, then he will generate the new release.
Or if you are in a hurry, I think you can ask someone with an apple App license to generate the release from the source on my branch.

**Comment by abrookins** [comment]
Hi! Yes, this feature sounds good to me. And so far the process has been that I review PRs, test them, and merge if they seem stable and valuable. This looks good to me, just have to find time to test it!

**Comment by abrookins** [comment]
As a side note, I bought a developer membership with Apple last year in order to merge some sVim features. That license will expire in August. So let's make all the improvements we want before then. 😬

**Comment by abrookins** [comment]
A new beta release is now available to install: https://github.com/flipxfx/sVim/releases/tag/1.0.7-beta.1

**Comment by ShiranC** [comment]
I installed the beta release. The default mappings ("f", "shift+f", "ctrl+shift+f") work as expected. However, I was not able to map these functions to other Keyboard commands as shown below:

map  ";"  createForegroundHint
map  "shift+;"  createTabbedHint

Thanks!

Shiran
----------------------------------
Sent from my iPhone
----------------------------------


On Mar 16, 2018 at 20:53:01 PDT, Andrew Brookins <notifications@github.com> wrote:


A new beta release is now available to install: https://github.com/flipxfx/sVim/releases/tag/1.0.7-beta.1

**Comment by luchenyuxx** [comment]
@ShiranC 
It works fine on my side with the new key binding.
Try to omit ";" at the end of the line if you have any.

**Comment by ShiranC** [comment]
Thanks @luchenyuxx  !
It was something in my sVimrc. 
It works great !
Thanks  @luchenyuxx  @abrookins  for your time and effort.

**Comment by abrookins** [comment]
The time and effort was all @luchenyuxx's, thanks @luchenyuxx!
