### ISSUE TITLE
Remove sVim

### ISSUE THREAD

**Issue by savvasmad** [flipxfx/sVim#89]
Good day!

Safari browser keeps using sVim configuration after removing the extension and i am unable to totally disable sVim extension. The browser keeps using it so i am unable to disable sVim hotkeys.

How can i totally remove/disable sVim hotkeys/extension?

Thanks in advance

**Comment by savvasmad** [comment]
@luchenyuxx 

No, i don't the extension is uninstalled but looks like it's not as sVim hotkeys are active, pretty weird.

**Comment by luchenyuxx** [comment]
@savvasmad 
Will restarting Safari fix the issue?

**Comment by savvasmad** [comment]
@luchenyuxx 

Restarting Safari / PC doesn't help

**Comment by luchenyuxx** [comment]
@savvasmad 
That's really weird, as sVim has no way to control the uninstall process of Safari.
Are you able to use hot key (by default 't') to open a new empty tab?

**Comment by savvasmad** [comment]
@luchenyuxx 

Yes, i am. 
All default sVim hotkeys are enabled "t" - new tab, "w" close tab...

**Comment by luchenyuxx** [comment]
@savvasmad 
sVim doesn't have "w" as close tab, "w" is open a new window? You have other plugins installed?

**Comment by abrookins** [comment]
I hope you figured this out. If Safari isn't removing the plugin correctly, I'm afraid that's beyond our ability to fix!
